#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Silkscreen the function of every connector pin, per connectors.md.

    python3 tools/pin_labels.py              # report placement and collisions
    python3 tools/pin_labels.py --apply
    python3 tools/pin_labels.py --strip --apply     # remove them again
    python3 tools/pin_labels.py --lock --apply      # protect them from re-runs
    python3 tools/pin_labels.py --relock --apply    # regenerate even locked ones

WHY
---
connectors.md: "This board is assembled once and cabled differently for each
instrument, by hand, months apart. The loom is where the mistakes will be, not
the PCB. So print the function of every pin beside every connector."

WHAT DECIDES THE DESIGN
-----------------------
Pin pitch, and nothing else. At 2.50 mm pitch with 0.25 mm silk clearance, one
row of 1 mm text fits TWO characters -- not enough for "3V3", let alone
"PGOOD". Staggering alternate pins into two rows doubles the effective pitch to
5.00 mm and buys five characters, which covers every label here except MIC_RTN
(shortened to RTN).

So labels stagger into as many rows as the pitch demands:

    rows = ceil((label width + clearance) / pitch)

Most connectors need 2. J13A is JST-SH at 1.00 mm pitch and needs 3.

Connectors whose pins run in a LINE ACROSS the label direction do not stagger
at all -- a 1 mm line of text is 1.06 mm tall against a 2.50 mm pitch, so the
labels simply stack. That covers J1, J3, J4, J17, J18, J14 and the two columns
of J11.

MEASURE SILK, NOT COURTYARDS
----------------------------
Courtyard-to-courtyard says J1, J3, J4 and J13A have 0.94-1.51 mm and cannot be
labelled. That is the wrong measurement: a courtyard is a placement keepout, it
does not reserve silkscreen. Measured silk-to-silk, every connector on the
board has room -- those four on their OUTWARD side, toward the board edge,
where they have 3.8-4.2 mm.

BOARD-LEVEL TEXT, DELIBERATELY
------------------------------
The labels are gr_text on the board, not fp_text inside each footprint, so they
do NOT follow a connector that gets moved. That is the trade, and it is the
same one cycle.py makes with routing: the labels are a disposable rendering of
placement, regenerated by re-running this. Every object carries a uuid5 derived
from "caryatid-pinlabel-<ref>-<pin>", so --strip removes exactly what this tool
wrote and nothing a human placed.

MOVE A CONNECTOR AND THE LABELS DO NOT FOLLOW. Re-run this after any placement
change, and check the collision report rather than assuming.

LOCK ANYTHING YOU ADJUST BY HAND. A hand-moved label keeps the uuid this tool
gave it, so without a lock the next --apply silently reverts it to the computed
position -- the same trap the board already documents for copper. --lock marks
every label this tool owns; strip() then refuses to touch them and treats them
as obstacles instead, and --relock is the deliberate override.
"""
import sys, os, re, math, uuid

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import check_board as C

NS       = uuid.UUID("6ba7b810-9dad-11d1-80b4-00c04fd430c8")
SIZE     = 1.0     # absonus precedent: 1 x 1 mm on F.SilkS
THICK    = 0.15    # JLC's stroke floor, and what absonus was fabricated with
CLEAR    = 0.26    # the rule is 0.25; 0.01 of margin on a modelled extent
STANDOFF = 0.30    # from the connector's own silk outline to the first row
EDGE     = 0.30    # silk to board edge; KiCad applies the silk rule here too

# KiCad's stroke font is NOT monospaced, and assuming it is does not merely
# lose accuracy -- it loses the answer. A flat 0.78 advance put 77 labels down
# with the tool reporting zero clashes and DRC then reporting 38, because '+'
# is 1.238 and 'I' is 0.476, a 2.6x spread. These are measured from KiCad's own
# PCB_TEXT.GetBoundingBox() at size 1.0, thickness 0.15, and scale with size.
ADV = {
    "A": 0.857, "B": 1.000, "C": 1.000, "D": 1.000, "E": 0.905, "F": 0.857,
    "G": 1.000, "H": 1.048, "I": 0.476, "J": 0.762, "K": 1.000, "L": 0.810,
    "M": 1.143, "N": 1.048, "O": 1.048, "P": 1.000, "Q": 1.048, "R": 1.000,
    "S": 0.952, "T": 0.762, "U": 1.048, "V": 0.857, "W": 1.143, "X": 0.952,
    "Y": 0.857, "Z": 0.952, "0": 0.952, "1": 0.952, "2": 0.952, "3": 0.952,
    "4": 0.952, "5": 0.952, "6": 0.952, "7": 0.952, "8": 0.952, "9": 0.952,
    "+": 1.238, "_": 0.762, "-": 0.762, ".": 0.476, "/": 0.952,
}
PAD_W = 0.10       # GetBoundingBox adds thickness + this, whatever the size

# Net name -> what to print. The Seed pin name is used wherever there is one,
# because pinmap.md is keyed on it; the function goes in the docs, not on a
# 5-character label. Anything not listed is printed as-is after the sheet
# prefix is stripped, and over-long results are reported rather than truncated.
LABEL = {
    "GND": "GND", "+5V": "5V", "+3V3": "3V3", "+3V3A": "3V3A",
    "DC_IN": "DC", "VOUT": "VOUT", "EN_SW": "EN", "LAMP": "LAMP",
    "CHG_LED": "CHG", "PGOOD_LED": "PGOOD",
    "RGB_R": "RED", "RGB_G": "GRN", "RGB_B": "BLU",
    "SW1_RAW": "SW1", "SW2_RAW": "SW2", "SW3_RAW": "SW3",
    "OUT_L_J": "L", "OUT_R_J": "R",
    "MIC_L": "L", "MIC_R": "R", "MIC_RTN": "RTN",
}
MAXLEN = 5


def label_for(net):
    n = re.sub(r"^/[^/]*/", "", net or "")
    n = n.replace("~{", "").replace("}", "")
    if not n or n.startswith("unconnected-"):
        return "NC"
    if n in LABEL:
        return LABEL[n]
    n = re.sub(r"_[WS]$", "", n)          # A0_W -> A0, D0_S -> D0
    return LABEL.get(n, n)


def tw(s, size=SIZE):
    """KiCad's bounding-box width. Deliberately the bounding box and not the
    stroke extent: it runs about 1.1x the inked width, so a placement this
    accepts is one DRC accepts."""
    return sum(ADV.get(c, 1.143) for c in s) * size + THICK + PAD_W


def th(size=SIZE):
    """Inked height, which is exactly size + thickness at every size tested."""
    return size + THICK


def th_split(size=SIZE):
    """Ink above and below the anchor -- which are NOT equal.

    KiCad centres text on its em box, not on the ink, so a 1 mm label's ink
    runs -0.620 to +0.530 about the anchor rather than +/-0.575. Treating it as
    centred understates the upward reach by 0.045 mm, and 0.045 is precisely
    the gap between the 0.2448 DRC kept reporting and the 0.25 rule."""
    off = 0.0077 + 0.0375 * size          # fitted over 0.8, 0.85, 0.9, 1.0
    h = (size + THICK) / 2
    return h + off, h - off


# ---------------------------------------------------------------- geometry --

def seg_seg(a, b, c, d):
    def cross(o, p, q): return (p[0]-o[0])*(q[1]-o[1]) - (p[1]-o[1])*(q[0]-o[0])
    d1, d2 = cross(c, d, a), cross(c, d, b)
    d3, d4 = cross(a, b, c), cross(a, b, d)
    if ((d1 > 0) != (d2 > 0)) and ((d3 > 0) != (d4 > 0)): return 0.0
    def pt_seg(p, u, v):
        dx, dy = v[0]-u[0], v[1]-u[1]
        if dx == dy == 0: return math.hypot(p[0]-u[0], p[1]-u[1])
        t = max(0, min(1, ((p[0]-u[0])*dx + (p[1]-u[1])*dy) / (dx*dx + dy*dy)))
        return math.hypot(p[0]-(u[0]+t*dx), p[1]-(u[1]+t*dy))
    return min(pt_seg(a, c, d), pt_seg(b, c, d), pt_seg(c, a, b), pt_seg(d, a, b))


def seg_rect(p1, p2, r):
    x0, y0, x1, y1 = r
    if (min(p1[0], p2[0]) <= x1 and max(p1[0], p2[0]) >= x0 and
            min(p1[1], p2[1]) <= y1 and max(p1[1], p2[1]) >= y0):
        inside = lambda p: x0 <= p[0] <= x1 and y0 <= p[1] <= y1
        if inside(p1) or inside(p2): return 0.0
    e = [((x0, y0), (x1, y0)), ((x1, y0), (x1, y1)),
         ((x1, y1), (x0, y1)), ((x0, y1), (x0, y0))]
    return min(seg_seg(p1, p2, a, b) for a, b in e)


def rect_rect(a, b):
    dx = max(a[0]-b[2], b[0]-a[2], 0.0)
    dy = max(a[1]-b[3], b[1]-a[3], 0.0)
    return math.hypot(dx, dy)


class Obstacles:
    """Everything a label must stay clear of: foreign silk, every pad, and the
    board edge. Pads matter because silk over exposed copper is ink on a
    solderable surface -- KiCad calls it silk_over_copper."""

    def __init__(self, B, skip_uuids=()):
        self.segs, self.rects = [], []
        for p in B.parts:
            for m in re.finditer(r"\(fp_(?:line|rect|arc|circle|poly)", p["blk"]):
                blk = C.sexp(p["blk"], m.start())
                if '"F.SilkS"' not in blk: continue
                # A silk line is 0.12 mm WIDE and DRC measures edge to edge, so
                # its ink reaches 0.06 mm past the centreline stored in the
                # file. Ignoring that is worth exactly 0.06 mm, which is enough
                # to turn a 0.25 mm clearance into the 0.24 mm DRC reports.
                wm = re.search(r"\(width ([\d.]+)\)", blk)
                hw = (float(wm.group(1)) if wm else 0.12) / 2
                pts = [B._xform(p, float(a), float(b)) for a, b in
                       re.findall(r"\((?:start|end|xy|center|mid) ([-\d.]+) ([-\d.]+)\)", blk)]
                for i in range(len(pts) - 1):
                    self.segs.append((pts[i], pts[i+1], p["ref"], hw))
                if len(pts) == 1:
                    self.segs.append((pts[0], pts[0], p["ref"], hw))
            for pm in re.finditer(r'\(property "(Reference|Value)" "([^"]*)"', p["blk"]):
                pb = C.sexp(p["blk"], pm.start())
                if "(hide yes)" in pb or "SilkS" not in pb: continue
                pa = re.search(r"\(at ([-\d.]+) ([-\d.]+)", pb)
                sz = re.search(r"\(size ([\d.]+) ([\d.]+)\)", pb)
                if not (pa and sz): continue
                x, y = B._xform(p, float(pa.group(1)), float(pa.group(2)))
                rot = re.search(r"\(at [-\d.]+ [-\d.]+ ([-\d.]+)\)", pb)
                hw = tw(pm.group(2), float(sz.group(1))) / 2
                hh = th(float(sz.group(2))) / 2
                if rot and abs(float(rot.group(1))) % 180 == 90: hw, hh = hh, hw
                self.rects.append((x-hw, y-hh, x+hw, y+hh, f"{p['ref']}:{pm.group(1)}"))
            for pd in B.pads(p):
                self.rects.append((pd["x"]-pd["w"]/2, pd["y"]-pd["h"]/2,
                                   pd["x"]+pd["w"]/2, pd["y"]+pd["h"]/2,
                                   f"{p['ref']}-{pd['num']}"))

    def clash(self, box, need):
        for a, b, who, hw in self.segs:
            if seg_rect(a, b, box) < need + hw: return who
        for x0, y0, x1, y1, who in self.rects:
            if rect_rect(box, (x0, y0, x1, y1)) < need: return who
        return None

    def add_label(self, box, who):
        """Labels already placed are obstacles for the next connector. Without
        this, J15's rows and J16's rows are each individually clear and land on
        top of each other."""
        self.rects.append((box[0], box[1], box[2], box[3], who))


# ---------------------------------------------------------------- placement --

def silk_box(B, p):
    xs, ys = [], []
    for m in re.finditer(r"\(fp_(?:line|rect|arc|circle|poly)", p["blk"]):
        blk = C.sexp(p["blk"], m.start())
        if '"F.SilkS"' not in blk: continue
        for a, b in re.findall(r"\((?:start|end|xy|center|mid) ([-\d.]+) ([-\d.]+)\)", blk):
            x, y = B._xform(p, float(a), float(b))
            xs.append(x); ys.append(y)
    if not xs: return None
    return (min(xs), min(ys), max(xs), max(ys))


def classify(pads):
    """How the pins are arranged, which is what decides where labels can go."""
    xs = sorted({round(d["x"], 2) for d in pads})
    ys = sorted({round(d["y"], 2) for d in pads})
    if len(xs) == 1: return "col", xs, ys          # one vertical column of pins
    if len(ys) == 1: return "row", xs, ys          # one horizontal row
    if len(xs) == 2 and len(ys) > 2: return "2col", xs, ys
    if len(ys) == 2 and len(xs) > 2: return "2row", xs, ys
    return "other", xs, ys


def plan(B, p, obst, outline):
    """Label boxes for one connector, or a reason it could not be placed."""
    ref = ref = p["ref"]
    # A pin whose label survived the strip is locked: KNOWN no longer holds its
    # uuid, so it drops out here and is neither replanned nor re-emitted.
    pads = [d for d in B.pads(p) if str(d["num"]).isdigit()
            and str(uuid.uuid5(NS, f"caryatid-pinlabel-{p['ref']}-{d['num']}")) in KNOWN]
    if not pads: return [], "no unlocked pins", []
    box = silk_box(B, p)
    if not box: return [], "no silk outline", []
    kind, xs, ys = classify(pads)
    if kind == "other": return [], f"unhandled pad pattern ({len(xs)}x{len(ys)})", []
    bx0, by0, bx1, by1 = box
    ox0, oy0, ox1, oy1 = outline
    h = th()

    def build(group, direction, pitch, so, size, rot, phase=0):
        """Lay `group` out on one side.

        Unrotated text beside a COLUMN of pins needs no stagger -- a line is
        1.06 mm tall against a 2.5 mm pitch, so labels simply stack, and the
        constraint is how much width the side offers. Rotating them 90 degrees
        swaps that: width becomes cheap and the pitch has to be staggered
        across columns instead. That is the escape for a connector with a long
        label and a near board edge, which is exactly J4's PGOOD."""
        h = th(size)
        up, dn = th_split(size)
        out = []
        if direction in ("up", "down"):
            wmax = max(tw(g["label"], size) for g in group)
            rows = max(1, math.ceil((wmax + CLEAR) / pitch)) if pitch else 1
            for i, g in enumerate(sorted(group, key=lambda q: q["x"])):
                r = (i + phase) % rows
                off = so + h/2 + r*(h + CLEAR)
                cy = (by0 - off) if direction == "up" else (by1 + off)
                w = tw(g["label"], size)
                out.append(dict(g, cx=g["x"], cy=cy, just="", size=size, rot=0,
                                bb=(g["x"]-w/2, cy-up, g["x"]+w/2, cy+dn)))
            return out, rows
        if rot:
            wmax = max(tw(g["label"], size) for g in group)
            cols = max(1, math.ceil((wmax + CLEAR) / pitch)) if pitch else 1
            for i, g in enumerate(sorted(group, key=lambda q: q["y"])):
                c = (i + phase) % cols
                off = so + h/2 + c*(h + CLEAR)
                cx = (bx0 - off) if direction == "left" else (bx1 + off)
                w = tw(g["label"], size)
                # rotated: the asymmetry lands on an axis we do not track, so
                # take the worst case on both sides rather than guess which
                out.append(dict(g, cx=cx, cy=g["y"], just="", size=size, rot=90,
                                bb=(cx-up, g["y"]-w/2, cx+up, g["y"]+w/2)))
            return out, cols
        for g in group:
            w = tw(g["label"], size)
            if direction == "left":
                ax = bx0 - so
                out.append(dict(g, cx=ax, cy=g["y"], just="right", size=size, rot=0,
                                bb=(ax-w, g["y"]-up, ax, g["y"]+dn)))
            else:
                ax = bx1 + so
                out.append(dict(g, cx=ax, cy=g["y"], just="left", size=size, rot=0,
                                bb=(ax, g["y"]-up, ax+w, g["y"]+dn)))
        return out, 1

    def score(placed):
        bad = []
        for q in placed:
            b = q["bb"]
            if (b[0] < ox0+EDGE or b[2] > ox1-EDGE or b[1] < oy0+EDGE or b[3] > oy1-EDGE):
                bad.append((q["label"], "board edge")); continue
            w = obst.clash(b, CLEAR)
            if w: bad.append((q["label"], w))
        return bad

    groups = []
    if kind in ("col", "row"):
        g = [dict(num=d["num"], label=label_for(d["net"]), x=d["x"], y=d["y"]) for d in pads]
        dirs = ("left", "right") if kind == "col" else ("up", "down")
        pitch = 0 if len(pads) < 2 else (
            min(abs(a["y"]-b["y"]) for a in g for b in g if a is not b) if kind == "col"
            else min(abs(a["x"]-b["x"]) for a in g for b in g if a is not b))
        groups.append((g, dirs, pitch))
    elif kind == "2col":
        pitch = min(abs(a-b) for a in ys for b in ys if a != b)
        for i, xv in enumerate(xs):
            g = [dict(num=d["num"], label=label_for(d["net"]), x=d["x"], y=d["y"])
                 for d in pads if round(d["x"], 2) == xv]
            groups.append((g, ("left",) if i == 0 else ("right",), pitch))
    else:  # 2row
        pitch = min(abs(a-b) for a in xs for b in xs if a != b)
        for i, yv in enumerate(ys):
            g = [dict(num=d["num"], label=label_for(d["net"]), x=d["x"], y=d["y"])
                 for d in pads if round(d["y"], 2) == yv]
            groups.append((g, ("up",) if i == 0 else ("down",), pitch))

    # Try each allowed side, and at each side try pushing the labels further
    # out. Most collisions are with something immediately beside the connector
    # -- a resistor, a neighbouring connector's outline -- and clear at a
    # slightly larger standoff rather than needing a different side.
    # Search side, then standoff, then text size, then rotation -- in that
    # order of preference, so a connector only gives up 1 mm text or turns its
    # labels sideways when the plain arrangement genuinely does not fit.
    result, notes, bad_all = [], [], []
    for g, dirs, pitch in groups:
        best = None
        # Size outermost: turning labels sideways at full height beats shrinking
        # them. 0.8 mm is JLC's minimum text height and 0.15 is its minimum
        # stroke, so a 0.8 mm label sits on BOTH floors at once.
        for size in (SIZE, 0.9, 0.85, 0.8):
            for rot in ((False, True) if kind == "col" else (False,)):
                for dr in dirs:
                    # Fine steps near the bottom: J13A needs a standoff
                    # between 0.31 and 0.32 mm -- above its own outline's ink,
                    # below where the third row runs off the board edge. A
                    # 0.30 -> 0.60 jump steps straight over the only answer.
                    for so in (STANDOFF, 0.35, 0.40, 0.45, 0.6, 0.9, 1.2, 1.6, 2.0):
                        for phase in range(4):
                            placed, rows = build(g, dr, pitch, so, size, rot, phase)
                            s = score(placed)
                            if best is None or len(s) < len(best[0]):
                                best = (s, placed, dr, rows, so, size, rot)
                            if not s: break
                            if phase + 1 >= rows: break
                        if not best[0]: break
                    if not best[0]: break
                if not best[0]: break
            if not best[0]: break
        s, placed, dr, rows, so, size, rot = best
        result += placed
        bad_all += s
        for q in placed:
            obst.add_label(q["bb"], f"{ref}-{q['label']}")
        tag = f"{dr}{'' if rows == 1 else f' x{rows}'}"
        if rot: tag += " rot"
        if size != SIZE: tag += f" @{size:g}"
        if so != STANDOFF: tag += f" +{so:g}"
        notes.append(tag + (f" [{len(s)} clash]" if s else ""))
    return result, ", ".join(notes), bad_all


# ------------------------------------------------------------------- output --

def emit(t, labels):
    at = t.rindex("\n\t(gr_line") if "\n\t(gr_line" in t else t.rindex("\n)")
    chunks = []
    for L in labels:
        just = f"\n\t\t\t(justify {L['just']})" if L["just"] else ""
        rot = f" {L['rot']:g}" if L.get("rot") else ""
        s = L.get("size", SIZE)
        chunks.append(
            f'\n\t(gr_text "{L["label"]}"\n'
            f'\t\t(at {L["cx"]:.4f} {L["cy"]:.4f}{rot})\n'
            f'\t\t(layer "F.SilkS")\n'
            f'\t\t(uuid "{L["uuid"]}")\n'
            f'\t\t(effects\n\t\t\t(font\n\t\t\t\t(size {s:g} {s:g})\n'
            f'\t\t\t\t(thickness {THICK:g})\n\t\t\t){just}\n\t\t)\n\t)')
    return t[:at] + "".join(chunks) + t[at:]


def strip(t, force=False):
    """Remove this tool's own labels -- but NEVER a locked one.

    Hand-adjusted labels keep the uuid the tool gave them, so without this a
    plain --apply silently reverts every manual nudge to the computed position.
    That is the same trap the repo already documents for copper ("lock any
    copper you place by hand"), and the same answer: cycle.py's strip_copper()
    skips (locked yes), so this does too. --relock is how a locked label gets
    regenerated deliberately rather than by accident."""
    n, kept = 0, 0
    while True:
        hit = None
        for m in re.finditer(r"^\t\(gr_text\b", t, re.M):
            blk = C.sexp(t, m.start()+1)
            u = re.search(r'\(uuid "([^"]+)"\)', blk)
            if not (u and u.group(1) in KNOWN): continue
            if "(locked yes)" in blk and not force:
                kept += 1; KNOWN.discard(u.group(1)); continue
            e = m.start()+1+len(blk)
            while e < len(t) and t[e] == "\n": e += 1
            hit = (m.start(), e); break
        if not hit: return t, n, kept
        t = t[:hit[0]] + t[hit[1]:]; n += 1


def lock_all(t):
    """Mark every label this tool owns as locked, in place."""
    n = 0
    for m in reversed(list(re.finditer(r"^\t\(gr_text \"", t, re.M))):
        blk = C.sexp(t, m.start()+1)
        u = re.search(r'\(uuid "([^"]+)"\)', blk)
        if not (u and u.group(1) in KNOWN) or "(locked yes)" in blk: continue
        head = blk.index("\n") + 1
        t = t[:m.start()+1] + blk[:head] + "\t\t(locked yes)\n" + blk[head:] \
            + t[m.start()+1+len(blk):]
        n += 1
    return t, n


KNOWN = set()


def surviving_labels(t):
    """Boxes of every F.SilkS gr_text still in the file after a strip.

    A locked label is not regenerated, but it is still ink on the board -- the
    next connector along has to route around it, so it has to be an obstacle."""
    out = []
    for m in re.finditer(r"^\t\(gr_text \"([^\"]*)\"", t, re.M):
        blk = C.sexp(t, m.start()+1)
        if '"F.SilkS"' not in blk: continue
        at = re.search(r"\(at ([-\d.]+) ([-\d.]+)(?: ([-\d.]+))?\)", blk)
        sm = re.search(r"\(size ([\d.]+)", blk)
        if not (at and sm): continue
        x, y, rot = float(at.group(1)), float(at.group(2)), float(at.group(3) or 0)
        size = float(sm.group(1))
        w = tw(m.group(1), size)
        up, dn = th_split(size)
        ju = re.search(r"\(justify ([a-z ]+)\)", blk)
        j = ju.group(1) if ju else ""
        if abs(rot) % 180 == 90:
            box = (x - up, y - w/2, x + up, y + w/2)
        elif "right" in j:
            box = (x - w, y - up, x, y + dn)
        elif "left" in j:
            box = (x, y - up, x + w, y + dn)
        else:
            box = (x - w/2, y - up, x + w/2, y + dn)
        out.append((box, f"locked '{m.group(1)}'"))
    return out


def main():
    apply_ = "--apply" in sys.argv
    B = C.Board(C.PCB)
    t = B.t
    outline = B.outline

    conns = [p for p in B.parts if re.match(r"^J\d", p["ref"])]
    for p in conns:
        for d in B.pads(p):
            KNOWN.add(str(uuid.uuid5(NS, f"caryatid-pinlabel-{p['ref']}-{d['num']}")))

    if "--lock" in sys.argv:
        t, n = lock_all(t)
        print(f"  locked {n} labels ({len(KNOWN)} owned by this tool)")
        if apply_: open(C.PCB, "w").write(t)
        else: print("  dry run -- pass --apply to write")
        return 0

    force = "--relock" in sys.argv
    if "--strip" in sys.argv:
        t, n, kept = strip(t, force)
        print(f"  removed {n} generated labels"
              + (f", kept {kept} locked (--relock to take those too)" if kept else ""))
        if apply_: open(C.PCB, "w").write(t)
        else: print("  dry run -- pass --apply to write")
        return 0

    t, removed, kept = strip(t, force)         # regenerate from clean
    if removed: print(f"  removed {removed} labels from a previous run")
    if kept: print(f"  kept {kept} LOCKED labels -- not regenerated, "
                   f"and treated as obstacles (--relock to override)")
    if removed or kept: print()
    B = C.Board.__new__(C.Board); C.Board.__init__(B, C.PCB)
    B.t = t
    B.parts = C.Board(C.PCB).parts             # placement is unchanged by strip
    obst = Obstacles(B)
    for box, name in surviving_labels(t):      # locked ones still occupy space
        obst.add_label(box, name)

    all_labels, clashes, longs = [], 0, []
    print(f"  {'ref':<6} {'pins':>4}  {'placement':<26} labels")
    detail = []
    for p in sorted(conns, key=lambda q: q["ref"]):
        placed, note, bad = plan(B, p, obst, outline)
        if not placed:
            print(f"  {p['ref']:<6} {'':>4}  {note}")
            continue
        for L in placed:
            L["uuid"] = str(uuid.uuid5(NS, f"caryatid-pinlabel-{p['ref']}-{L['num']}"))
            if len(L["label"]) > MAXLEN: longs.append((p["ref"], L["num"], L["label"]))
        clashes += len(bad)
        detail += [(p["ref"], lb, who) for lb, who in bad]
        txt = " ".join(f"{L['label']}" for L in sorted(placed, key=lambda q: int(q["num"])))
        print(f"  {p['ref']:<6} {len(placed):>4}  {note:<28} {txt}")
        all_labels += placed

    print(f"\n  {len(all_labels)} labels, {clashes} still clashing")
    for r, lb, who in detail:
        print(f"    {r}-{lb:<6} hits {who}")
    if longs:
        print(f"  over {MAXLEN} characters: " + ", ".join(f"{r}-{n} {l}" for r, n, l in longs))
    if not apply_:
        print("  dry run -- pass --apply to write")
        return 0
    t = emit(t, all_labels)
    open(C.PCB, "w").write(t)
    d = sum(1 if c == "(" else -1 if c == ")" else 0 for c in t)
    print(f"  wrote {len(all_labels)} labels, paren balance {d}")
    return 0 if d == 0 else 1


if __name__ == "__main__":
    sys.exit(main())